# Question 3
Write the Python function to generate the Adjoint Matrix of 3 x 3 Matrix, without using NumPy 
libraries. (Use the function in Question No: 1 and 2, function for matrix transpose in question 
number 2 in assignment No. 1).

Write python code find out the Adjoint Matrix of the given 3 X3 Matrix using this function.

# Input:
Elements of the 3 X 3 Matrix

# Output:
Adjoint Matrix corresponding to the given 3 x3 Matrix.

# Answer with code :

# Matrix - A Definition
A matrix is a rectangular array of numbers or symbols which are generally arranged in rows and columns.The order of the matrix is defined as the number of rows and columns.The entries are the numbers in the matrix and each number is known as an element.The plural of matrix is matrices.The size of a matrix is referred to as ‘n by m’ matrix and is written as m×n, where n is the number of rows and m is the number of columns.

# Adjoint of a Matrix - A Definition and how to find it
The adjoint of a matrix B is the transpose of the cofactor matrix of C. The adjoint of a square matrix C is denoted by 
adj C. Let C = [cij] be a square matrix of order n. The three important steps involved in finding the adjoint of a matrix are:

1.Find the minor matrix M of all the elements of matrix B.

2.Find the cofactor matrix C of all the minor elements of matrix M.

3.Find the adj B by taking the transpose of the cofactor matrix C.

# User Defined Function for Finding the Minor of used inputed matrix 

# Function for fetching the Transpose of Cofactor matrix

In [1]:
def FetchMatrixTranspose(fmc,m_row,m_col): #function for finding the transpose
    A = [([0]*m_col) for i in range(m_row)] #Here we creating an zero matrix 'M' having same size as our input matrix
    for i in range(m_row):# Two variable to access the matrix elements 
        for j in range(m_col): #Loop counter with m_col
            A[j][i] = fmc[i][j] #logic of interchanging rows and columns of the matrix
    return A

# Function for fetching the Cofactor matrix

In [2]:
def FetchMatrixCofactor(m,fmm,m_row,m_col): #function for fetching matrix 
    C = [([0]*m_col) for i in range(m_row)] #Here we creating an zero matrix 'M' having same size as our input matrix
    for r in range(len(m)): # Two variable to access the matrix elements 
        for c in range(len(m)): # #Loop counter with m_col
            C[r][c]=(-1)**(r+c)*fmm[r][c] #logic of elements of cofactor matrix with(-1)^(row and column index values)
    return C

# Function for fetching the Minor Matrix

In [3]:
def FetchMatrixMinor(m,m_row,m_col):
    M = [([0]*m_col) for i in range(m_row)] #Here we creating an zero matrix 'M' having same size as our input matrix
    for r in range(len(m)+1): # Two variable to access the matrix elements 
        for c in range(len(m)+1):
           M[len(m)-3][len(m)-3]=m[len(m)-2][len(m)-2]*m[len(m)-1][len(m)-1]-m[len(m)-2][len(m)-1]*m[len(m)-1][len(m)-2] #finding the M11 element of minor matrix by finding the determinant of sub-matrix obtainred by elimiating 1st row and 1st column   
           M[len(m)-3][len(m)-2]=m[len(m)-2][len(m)-3]*m[len(m)-1][len(m)-1]-m[len(m)-2][len(m)-1]*m[len(m)-1][len(m)-3] #finding the M11 element of minor matrix by finding the determinant of sub-matrix obtainred by elimiating 1st row and 2nd column
           M[len(m)-3][len(m)-1]=m[len(m)-2][len(m)-3]*m[len(m)-1][len(m)-2]-m[len(m)-2][len(m)-2]*m[len(m)-1][len(m)-3] #finding the M11 element of minor matrix by finding the determinant of sub-matrix obtainred by elimiating 1st row and 3rd column
           M[len(m)-2][len(m)-3]=m[len(m)-3][len(m)-2]*m[len(m)-1][len(m)-1]-m[len(m)-3][len(m)-1]*m[len(m)-1][len(m)-2] #finding the M11 element of minor matrix by finding the determinant of sub-matrix obtainred by elimiating 2nd row and 1st column
           M[len(m)-2][len(m)-2]=m[len(m)-3][len(m)-3]*m[len(m)-1][len(m)-1]-m[len(m)-3][len(m)-1]*m[len(m)-1][len(m)-3] #finding the M11 element of minor matrix by finding the determinant of sub-matrix obtainred by elimiating 2nd row and 2nd column
           M[len(m)-2][len(m)-1]=m[len(m)-3][len(m)-3]*m[len(m)-1][len(m)-2]-m[len(m)-3][len(m)-2]*m[len(m)-1][len(m)-3] #finding the M11 element of minor matrix by finding the determinant of sub-matrix obtainred by elimiating 2nd row and 3rd column
           M[len(m)-1][len(m)-3]=m[len(m)-3][len(m)-2]*m[len(m)-2][len(m)-1]-m[len(m)-3][len(m)-1]*m[len(m)-2][len(m)-2] #finding the M11 element of minor matrix by finding the determinant of sub-matrix obtainred by elimiating 3rd row and 1st column
           M[len(m)-1][len(m)-2]=m[len(m)-3][len(m)-3]*m[len(m)-2][len(m)-1]-m[len(m)-3][len(m)-1]*m[len(m)-2][len(m)-3] #finding the M11 element of minor matrix by finding the determinant of sub-matrix obtainred by elimiating 3rd row and 2nd column
           M[len(m)-1][len(m)-1]=m[len(m)-3][len(m)-3]*m[len(m)-2][len(m)-2]-m[len(m)-3][len(m)-2]*m[len(m)-2][len(m)-3] #finding the M11 element of minor matrix by finding the determinant of sub-matrix obtainred by elimiating 3rd row and 3rd column
        return M

# Main Program

In [4]:
#Taking the number of rows and columns for matrix as input from the user
m_row = int(input('Enter number of row of matrix 1: '))
m_col = int(input('Enter number of columns of matrix 1: '))

#Create a first matrix using input() function and nested list comprehension
m = [[int(input(f'column {j+1} -> Enter {i+1} element for Matrix One:')) for j in range(m_col)] for i in range(m_row)]

#Print inputed Matrix
print('User Inputed Matrix: ')
for i in m:
    print(i)

#calling the function FetchMatrixMinor passing row number, column number and matrix itself, for fetching minor matrix of inputed matrix
fmm = FetchMatrixMinor(m,m_row,m_col)
#calling the function FetchMatrixCofactor passing row number, column number and matrix,minor matrix , for fetching cofactor matrix of inputed minior matrix
fmc=FetchMatrixCofactor(m,fmm,m_row,m_col)
#calling the function FetchMatrixTranspose passing row number, column number and cofactor matrix , for fetching adjoint matrix of inputed cofactor matrix
fmt=FetchMatrixTranspose(fmc,m_row,m_col)
print('The Adjoint Matrix')
for i in fmt: #printing the adjoint matrix as a 3X3 matrix from the returned cofactor matrix
    print(i)  

Enter number of row of matrix 1: 3
Enter number of columns of matrix 1: 3
column 1 -> Enter 1 element for Matrix One:2
column 2 -> Enter 1 element for Matrix One:4
column 3 -> Enter 1 element for Matrix One:6
column 1 -> Enter 2 element for Matrix One:3
column 2 -> Enter 2 element for Matrix One:6
column 3 -> Enter 2 element for Matrix One:9
column 1 -> Enter 3 element for Matrix One:5
column 2 -> Enter 3 element for Matrix One:15
column 3 -> Enter 3 element for Matrix One:2
User Inputed Matrix: 
[2, 4, 6]
[3, 6, 9]
[5, 15, 2]
The Adjoint Matrix
[-123, 82, 0]
[39, -26, 0]
[15, -10, 0]


  # Performing validation using Numpy

In [14]:
import numpy as np #importing libraries

cofactor = np.array(fmc) #creating numpy array for cofactor matrix

adjnt = cofactor.T #taking the transpose of the cofactor matrix 

print(adjnt) #printing the results

[[-123   82    0]
 [  39  -26    0]
 [  15  -10    0]]
